# https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md
[pre-commit]
parallel = true

[pre-commit.commands.lint]
glob = "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"
run = "pnpm biome check --write --no-errors-on-unmatched --files-ignore-unknown=true --colors=off {staged_files}"
stage_fixed = true

# [pre-commit.commands.lychee]
# glob = "*.md"
# run = "lychee --max-concurrency 3 -v {staged_files}"
